export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_SORT_VALUE = 'UPDATE_SORT_VALUE';
export const UPDATE_SELECTED_TODO = 'UPDATE_SELECTED_TODO';
export const TODOS = "TODOS"